// AUTO-GENERATED by scripts/convert-all.mjs. Markup mirrors the original template;
// styling comes from /assets/css/styles.css. Re-run the script to regenerate.
export default function ChangelogPage() {
  return (
    <>
      <section className="style-guide-section">
                <div className="container large-container">
                  <div className="wrapper license-wrapper">
                    <div className="block-wrap">
                      <h1 className="center-align reveal">
                        Changelog
                      </h1>
                      <p className="center-align reveal">
                        Stay up to date with the latest improvements, fixes, and new features we’ve added to Senti.
                      </p>
                    </div>
                    <div className="changelog-wrap">
                      <div className="changelog-card reveal">
                        <div className="changelog-lists-block">
                          <div className="changelog-card-title">
                            V1.0 – Performance Boost
                          </div>
                          <ul className="changelog-list-block" role="list">
                            <li>
                              Improved load time for the homepage by optimizing image assets.
                            </li>
                            <li>
                              Adjusted spacing in Selected Work section for better readability.
                            </li>
                            <li>
                              Fixed hover bug on mobile navbar.
                            </li>
                          </ul>
                        </div>
                        <div className="small-paragraph ash">
                          July 23, 2025
                        </div>
                      </div>
                      <div className="changelog-card reveal">
                        <div className="changelog-lists-block">
                          <div className="changelog-card-title">
                            v1.0.2 – Minor Tweaks
                          </div>
                          <ul className="changelog-list-block" role="list">
                            <li>
                              Replaced low-res hero image with higher quality version.
                            </li>
                            <li>
                              Adjusted padding in footer for better visual balance.
                            </li>
                            <li>
                              Updated favicon and page title.
                            </li>
                          </ul>
                        </div>
                        <div className="small-paragraph ash">
                          July 23, 2025
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="cta-section">
                <div className="container large-container">
                  <div className="wrapper cta-wrapper">
                    <div className="cta-wrap">
                      <div className="cta-flex">
                        <h2 className="white-text cta-title">
                          Unlock Smarter Analytics Now
                        </h2>
                        <p className="cta-para">
                          Start free today or book a demo to see how Virion transforms your data.
                        </p>
                        <div className="cta-buttons">
                          <a className="cta-button" href="/contact">
                            <div className="text-overflow">
                              <div className="button-text _01">
                                Get Started
                              </div>
                              <div className="button-text _02">
                                Get Started
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
    </>
  );
}
