// AUTO-GENERATED by scripts/convert-all.mjs. Markup mirrors the original template;
// styling comes from /assets/css/styles.css. Re-run the script to regenerate.
export default function AboutPage() {
  return (
    <>
      <section className="home-hero-section">
                <div className="container large-container">
                  <div className="wrapper about-hero-wrapper">
                    <div className="hero-top-contents">
                      <h1 className="hero-title reveal">
                        Take Control on Your Statistic Page
                      </h1>
                      <p className="hero-para reveal">
                        Amet neque mi tellus gravida sollicitudin. Sapien ultricies lobortis pellentesque at auctor. notifications, upload filesAmet neque
                      </p>
                      <div className="hero-buttons reveal">
                        <a className="primary-button" href="/signup">
                          <div className="text-overflow">
                            <div className="button-text _01">
                              Create your Analysts
                            </div>
                            <div className="button-text _02">
                              Create your Analysts
                            </div>
                          </div>
                        </a>
                      </div>
                    </div>
                    <div className="about-collections">
                      <div className="about-top-collection">
                        <div className="team-card">
                          <div className="overflow-hidden team-overflow">
                            <img alt="Team Member" className="team-member" loading="lazy" sizes="(max-width: 726px) 100vw, 726px" src="/assets/images/Team-Member-1_1.webp" srcSet="/assets/images/Team-Member-1_1Team-Member-1.webp 500w, /assets/images/Team-Member-1_1Team-Member-1.webp 800w, /assets/images/Team-Member-1_1Team-Member-1.webp 1080w, /assets/images/Team-Member-1_1.webp 1089w" />
                          </div>
                          <div className="team-member-detail">
                            <div className="team-member-flex">
                              <div className="team-member-name">
                                Noah Steele
                              </div>
                              <div>
                                Founder &amp; CEO
                              </div>
                            </div>
                            <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                              <svg className="linkedin-icon" fill="none" viewBox="0 0 32 32" width="100%" xmlns="http://www.w3.org/2000/svg">
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="currentColor" fillRule="evenodd">
                                </path>
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="url(#pattern0_69_2235)" fill-opacity="0.07" fillRule="evenodd">
                                </path>
                              </svg>
                              <div className="seo">
                                SEO Text
                              </div>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className="about-middle-collection">
                        <div className="team-card">
                          <div className="overflow-hidden team-overflow">
                            <img alt="Team Member" className="team-member" loading="lazy" sizes="(max-width: 726px) 100vw, 726px" src="/assets/images/Team-Member-2_1.webp" srcSet="/assets/images/Team-Member-2_1Team-Member-2.webp 500w, /assets/images/Team-Member-2_1.webp 726w" />
                          </div>
                          <div className="team-member-detail">
                            <div className="team-member-flex">
                              <div className="team-member-name">
                                Daniel Roberts
                              </div>
                              <div>
                                Head of Product
                              </div>
                            </div>
                            <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                              <svg className="linkedin-icon" fill="none" viewBox="0 0 32 32" width="100%" xmlns="http://www.w3.org/2000/svg">
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="currentColor" fillRule="evenodd">
                                </path>
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="url(#pattern0_69_2235)" fill-opacity="0.07" fillRule="evenodd">
                                </path>
                              </svg>
                              <div className="seo">
                                SEO Text
                              </div>
                            </a>
                          </div>
                        </div>
                        <div className="team-card">
                          <div className="overflow-hidden team-overflow">
                            <img alt="Team Member" className="team-member" loading="lazy" sizes="(max-width: 726px) 100vw, 726px" src="/assets/images/Team-Member-3_1.webp" srcSet="/assets/images/Team-Member-3_1Team-Member-3.webp 500w, /assets/images/Team-Member-3_1.webp 726w" />
                          </div>
                          <div className="team-member-detail">
                            <div className="team-member-flex">
                              <div className="team-member-name">
                                Fatima Lopez
                              </div>
                              <div>
                                Head of Marketing
                              </div>
                            </div>
                            <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                              <svg className="linkedin-icon" fill="none" viewBox="0 0 32 32" width="100%" xmlns="http://www.w3.org/2000/svg">
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="currentColor" fillRule="evenodd">
                                </path>
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="url(#pattern0_69_2235)" fill-opacity="0.07" fillRule="evenodd">
                                </path>
                              </svg>
                              <div className="seo">
                                SEO Text
                              </div>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className="about-middle-collection">
                        <div className="team-card">
                          <div className="overflow-hidden team-overflow">
                            <img alt="Team Member" className="team-member" loading="lazy" sizes="(max-width: 726px) 100vw, 726px" src="/assets/images/Team-Member-4_1.webp" srcSet="/assets/images/Team-Member-4_1Team-Member-4.webp 500w, /assets/images/Team-Member-4_1.webp 726w" />
                          </div>
                          <div className="team-member-detail">
                            <div className="team-member-flex">
                              <div className="team-member-name">
                                Sarah Johnson
                              </div>
                              <div>
                                Lead Data Scientist
                              </div>
                            </div>
                            <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                              <svg className="linkedin-icon" fill="none" viewBox="0 0 32 32" width="100%" xmlns="http://www.w3.org/2000/svg">
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="currentColor" fillRule="evenodd">
                                </path>
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="url(#pattern0_69_2235)" fill-opacity="0.07" fillRule="evenodd">
                                </path>
                              </svg>
                              <div className="seo">
                                SEO Text
                              </div>
                            </a>
                          </div>
                        </div>
                        <div className="team-card">
                          <div className="overflow-hidden team-overflow">
                            <img alt="Team Member" className="team-member" loading="lazy" sizes="(max-width: 726px) 100vw, 726px" src="/assets/images/Team-Member-5_1.webp" srcSet="/assets/images/Team-Member-5_1Team-Member-5.webp 500w, /assets/images/Team-Member-5_1.webp 726w" />
                          </div>
                          <div className="team-member-detail">
                            <div className="team-member-flex">
                              <div className="team-member-name">
                                Alex Morgan
                              </div>
                              <div>
                                UX/UI Designer
                              </div>
                            </div>
                            <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                              <svg className="linkedin-icon" fill="none" viewBox="0 0 32 32" width="100%" xmlns="http://www.w3.org/2000/svg">
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="currentColor" fillRule="evenodd">
                                </path>
                                <path clipRule="evenodd" d="M15.9234 2.33325H16.0759C18.9969 2.33324 21.2911 2.33323 23.0823 2.57404C24.9178 2.82083 26.3742 3.33687 27.5185 4.48113C28.6627 5.6254 29.1787 7.08175 29.4255 8.91728C29.6663 10.7085 29.6663 13.0028 29.6663 15.9237V16.0762C29.6663 18.9971 29.6663 21.2914 29.4255 23.0826C29.1787 24.9181 28.6627 26.3745 27.5185 27.5187C26.3742 28.663 24.9178 29.179 23.0823 29.4258C21.2911 29.6666 18.9969 29.6666 16.0759 29.6666H15.9234C13.0025 29.6666 10.7083 29.6666 8.91704 29.4258C7.0815 29.179 5.62515 28.663 4.48089 27.5187C3.33663 26.3745 2.82058 24.9181 2.57379 23.0826C2.33298 21.2914 2.33299 18.9971 2.33301 16.0762V15.9237C2.33299 13.0027 2.33298 10.7085 2.57379 8.91728C2.82058 7.08175 3.33663 5.6254 4.48089 4.48113C5.62515 3.33687 7.0815 2.82083 8.91704 2.57404C10.7082 2.33323 13.0025 2.33324 15.9234 2.33325ZM10.6689 13.9999C10.6689 13.2635 10.072 12.6666 9.33561 12.6666C8.59923 12.6666 8.00227 13.2635 8.00227 13.9999V22.6666C8.00227 23.403 8.59923 23.9999 9.33561 23.9999C10.072 23.9999 10.6689 23.403 10.6689 22.6666V13.9999ZM14.669 11.9999C15.2094 11.9999 15.6749 12.3215 15.8842 12.7838C16.6947 12.2866 17.6483 11.9999 18.669 11.9999C21.6145 11.9999 24.0023 14.3878 24.0023 17.3333V22.6666C24.0023 23.403 23.4053 23.9999 22.669 23.9999C21.9326 23.9999 21.3357 23.403 21.3357 22.6666V17.3333C21.3357 15.8605 20.1417 14.6666 18.669 14.6666C17.1962 14.6666 16.0023 15.8605 16.0023 17.3333V22.6666C16.0023 23.403 15.4053 23.9999 14.669 23.9999C13.9326 23.9999 13.3357 23.403 13.3357 22.6666V13.3333C13.3357 12.5969 13.9326 11.9999 14.669 11.9999ZM11.0127 9.33325C11.0127 10.2537 10.2665 10.9999 9.34603 10.9999H9.33405C8.41358 10.9999 7.66738 10.2537 7.66738 9.33325C7.66738 8.41277 8.41358 7.66659 9.33405 7.66659H9.34603C10.2665 7.66659 11.0127 8.41277 11.0127 9.33325Z" fill="url(#pattern0_69_2235)" fill-opacity="0.07" fillRule="evenodd">
                                </path>
                              </svg>
                              <div className="seo">
                                SEO Text
                              </div>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="founding-section">
                <div className="container large-container">
                  <div className="wrapper founding-wrapper">
                    <div className="founding-sticky">
                      <div className="subtitle-block reveal">
                        <div className="typography-title">
                          Founding story
                        </div>
                      </div>
                      <h2 className="heading-h2 left reveal">
                        The story behind Virion
                      </h2>
                    </div>
                    <div className="founding-details">
                      <div className="founding-desp reveal">
                        <p>
                          John, Shaq, and Robert first crossed paths at Virion—one of the UK’s leading digital banks—where they built and scaled the Data Science and Machine Learning functions from the ground up.
                        </p>
                        <p>
                          In Virion’s early days, low support volumes meant agents could deliver deeply personal, high-quality service. But as the company scaled, maintaining that level of care became increasingly difficult. Over the years, the trio led automation efforts across customer operations and financial crime systems—working at the intersection of AI, product, and regulatory compliance.
                        </p>
                        <p>
                          Inspired by the release of GPT-4, the idea for Virion was born. After countless weekends exploring what large language models could do, it became clear: the future of customer service in financial services could be fully automated—without sacrificing quality, safety, or compliance.
                        </p>
                        <p>
                          The team went into stealth mode for 14 months, refining an AI solution that financial institutions could actually trust. In 2024, Virion launched its flagship AI support agent—and it didn’t just match human performance, it exceeded it, delivering up to 98% customer satisfaction.
                        </p>
                        <p>
                          Today, Virion is a growing team of over 20 people. Backed by a successful Series A in 2025, the company is focused on its mission: delivering exceptional, compliant customer service at scale in highly regulated industries.
                        </p>
                      </div>
                      <div className="founding-author-block">
                        <div className="founding-img-block">
                          <img alt="Founding Image" className="founding-image" loading="lazy" sizes="(max-width: 2592px) 100vw, 2592px" src="/assets/images/Founding-Image_1.webp" srcSet="/assets/images/Founding-Image_1Founding-Image.webp 500w, /assets/images/Founding-Image_1Founding-Image.webp 800w, /assets/images/Founding-Image_1Founding-Image.webp 1080w, /assets/images/Founding-Image_1Founding-Image.webp 1600w, /assets/images/Founding-Image_1Founding-Image.webp 2000w, /assets/images/Founding-Image_1.webp 2592w" />
                        </div>
                        <div className="founding-name">
                          John, Robert, Kevin
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="number-section">
                <div className="container large-container">
                  <div className="wrapper number-wrapper">
                    <div className="number-top">
                      <div className="subtitle-block left reveal">
                        <div className="typography-title">
                          Number Says It All
                        </div>
                      </div>
                      <h3 className="heading-h3 reveal">
                        Your data, done right. At Virion, we turn cluttered information into clean, organized, and usable data quickly and accurately.
                      </h3>
                    </div>
                    <div className="number-cards">
                      <div className="number-card">
                        <div>
                          Total Value Locked
                        </div>
                        <div className="number-wrap">
                          <div className="number _01">
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              3
                            </h2>
                            <h2 className="counter-title">
                              4
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              6
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              8
                            </h2>
                            <h2 className="counter-title">
                              9
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                          </div>
                          <h2 className="counter-title">
                            B
                          </h2>
                          <h2 className="counter-title">
                            +
                          </h2>
                        </div>
                      </div>
                      <div className="number-card">
                        <div>
                          Total Transactions
                        </div>
                        <div className="number-wrap">
                          <div className="number _01">
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              3
                            </h2>
                            <h2 className="counter-title">
                              4
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              6
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              8
                            </h2>
                            <h2 className="counter-title">
                              9
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                          </div>
                          <div className="number _02">
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              3
                            </h2>
                            <h2 className="counter-title">
                              4
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              6
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              8
                            </h2>
                            <h2 className="counter-title">
                              9
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                          </div>
                          <div className="number _01">
                            <h2 className="counter-title">
                              0
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              3
                            </h2>
                            <h2 className="counter-title">
                              4
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              6
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              8
                            </h2>
                            <h2 className="counter-title">
                              9
                            </h2>
                            <h2 className="counter-title">
                              0
                            </h2>
                          </div>
                          <h2 className="counter-title">
                            M
                          </h2>
                        </div>
                      </div>
                      <div className="number-card">
                        <div>
                          Unique Wallets
                        </div>
                        <div className="number-wrap">
                          <div className="number _01">
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              3
                            </h2>
                            <h2 className="counter-title">
                              4
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              6
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              8
                            </h2>
                            <h2 className="counter-title">
                              9
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                          </div>
                          <h2 className="counter-title">
                            B
                          </h2>
                          <h2 className="counter-title">
                            +
                          </h2>
                        </div>
                      </div>
                      <div className="number-card">
                        <div>
                          Defi Chains
                        </div>
                        <div className="number-wrap">
                          <div className="number _01">
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              3
                            </h2>
                            <h2 className="counter-title">
                              4
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              6
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              8
                            </h2>
                            <h2 className="counter-title">
                              9
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                          </div>
                          <div className="number _02">
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              1
                            </h2>
                            <h2 className="counter-title">
                              2
                            </h2>
                            <h2 className="counter-title">
                              3
                            </h2>
                            <h2 className="counter-title">
                              4
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                            <h2 className="counter-title">
                              6
                            </h2>
                            <h2 className="counter-title">
                              7
                            </h2>
                            <h2 className="counter-title">
                              8
                            </h2>
                            <h2 className="counter-title">
                              9
                            </h2>
                            <h2 className="counter-title">
                              5
                            </h2>
                          </div>
                          <h2 className="counter-title">
                            +
                          </h2>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <div className="builder-height">
                <section className="builder-section">
                  <div className="container about-container">
                    <div className="wrapper about-wrapper">
                      <div className="builder-block">
                        <img alt="Builder Icon-1\" className="builder-icon-1 reveal" loading="lazy" sizes="100vw" src="/assets/images/Builder-Icon-1.webp" srcSet="/assets/images/Frame-2147236534-p-500.png 500w, /assets/images/Frame-2147236534-p-800.png 800w, /assets/images/Builder-Icon-1.webp 1020w" />
                        <img alt="Builder Icon-1\" className="builder-icon-2 reveal" loading="lazy" sizes="100vw" src="/assets/images/Builder-Icon-2.webp" srcSet="/assets/images/Frame-2147236535-p-500.png 500w, /assets/images/Frame-2147236535-p-800.png 800w, /assets/images/Builder-Icon-2.webp 916w" />
                        <h2 className="center-align builder-text reveal">
                          Ditch the modals. Our logic builder gets users to 100% onboarding fast.
                        </h2>
                        <img alt="Builder Icon-1\" className="builder-icon-3 reveal" loading="lazy" sizes="100vw" src="/assets/images/Builder-Icon-3.webp" srcSet="/assets/images/Frame-2147236536-p-500.png 500w, /assets/images/Frame-2147236536-p-800.png 800w, /assets/images/Builder-Icon-3.webp 1010w" />
                        <img alt="Builder Icon-1\" className="builder-icon-4 reveal" loading="lazy" sizes="100vw" src="/assets/images/Builder-Icon-2.webp" srcSet="/assets/images/Frame-2147236535-p-500.png 500w, /assets/images/Frame-2147236535-p-800.png 800w, /assets/images/Builder-Icon-2.webp 916w" />
                      </div>
                      <img alt="" className="about-card builder-1" loading="lazy" sizes="100vw" src="/assets/images/Builder-1_1.webp" srcSet="/assets/images/Builder-1_1-p-500.png 500w, /assets/images/Builder-1_1-p-800.png 800w, /assets/images/Builder-1_1Builder-1.webp 1080w, /assets/images/Builder-1_1.webp 1269w" />
                      <img alt="" className="about-card builder-2" loading="lazy" sizes="100vw" src="/assets/images/Builder-2_1.webp" srcSet="/assets/images/Builder-2_1Builder-2.webp 500w, /assets/images/Builder-2_1Builder-2.webp 800w, /assets/images/Builder-2_1Builder-2.webp 1080w, /assets/images/Builder-2_1.webp 1336w" />
                      <img alt="" className="about-card builder-3" loading="lazy" sizes="100vw" src="/assets/images/Builder-4_1.webp" srcSet="/assets/images/Builder-4_1Builder-4.webp 500w, /assets/images/Builder-4_1Builder-4.webp 800w, /assets/images/Builder-4_1Builder-4.webp 1080w, /assets/images/Builder-4_1.webp 1436w" />
                      <img alt="" className="about-card builder-4" loading="lazy" sizes="100vw" src="/assets/images/Builder-3_1.webp" srcSet="/assets/images/Builder-3_1Builder-3.webp 500w, /assets/images/Builder-3_1Builder-3.webp 800w, /assets/images/Builder-3_1Builder-3.webp 1080w, /assets/images/Builder-3_1.webp 1282w" />
                    </div>
                  </div>
                </section>
              </div>
              <section className="principals-section">
                <div className="container large-container">
                  <div className="wrapper principal-wrapper">
                    <div className="principals-top">
                      <div className="subtitle-block reveal">
                        <div className="typography-title">
                          Our Principals
                        </div>
                      </div>
                      <h2 className="heading-h2 principal-title reveal">
                        Our actions &amp; principals
                      </h2>
                    </div>
                    <div className="principals-cards">
                      <div className="reveal">
                        <div className="principals-card">
                          <div className="principal-icon-block">
                            <img alt="Principal Icon" className="principal-icon" loading="lazy" src="/assets/images/Principal-Icon-1.webp" />
                          </div>
                          <div className="principal-detail">
                            <div className="principal-card-title">
                              For Marketing Teams
                            </div>
                            <p>
                              Marketing teams can instantly see campaign performance, track ROI, and identify top-performing channels. With automated reports and real-time dashboards
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className="reveal">
                        <div className="principals-card">
                          <div className="principal-icon-block">
                            <img alt="Principal Icon" className="principal-icon" loading="lazy" src="/assets/images/Principal-Icon-2.webp" />
                          </div>
                          <div className="principal-detail">
                            <div className="principal-card-title">
                              Integrity in Action
                            </div>
                            <p>
                              Honesty, transparency, and accountability guide all our decisions and interactions. We believe long-term trust is built through ethical practices and consistent, open communication.
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className="reveal">
                        <div className="principals-card">
                          <div className="principal-icon-block">
                            <img alt="Principal Icon" className="principal-icon" loading="lazy" src="/assets/images/Principal-Icon-3.webp" />
                          </div>
                          <div className="principal-detail">
                            <div className="principal-card-title">
                              Innovation with Purpose
                            </div>
                            <p>
                              We embrace creativity and forward-thinking to stay ahead in a fast-changing market. Every innovative idea we serves a clear goal to elevate our clients' brands and performance.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="success-section">
                <div className="container large-container">
                  <div className="wrapper success-wrapper">
                    <div className="success-top">
                      <div className="subtitle-block reveal">
                        <div className="typography-title">
                          Success
                        </div>
                      </div>
                      <h2 className="heading-h2 success-title reveal">
                        My Journey of excellence
                      </h2>
                    </div>
                    <div className="success-cards reveal">
                      <div className="success-card _01">
                        <div className="success-no">
                          01
                        </div>
                        <div className="success-detail">
                          <div className="success-year">
                            2019
                          </div>
                          <div className="success-card-name">
                            Red Dot - Design Award
                          </div>
                        </div>
                        <img alt="Success Image" className="success-image" loading="lazy" sizes="(max-width: 1020px) 100vw, 1020px" src="/assets/images/Success-Image-1.webp" srcSet="/assets/images/Success-Image.webp 500w, /assets/images/Success-Image.webp 800w, /assets/images/Success-Image-1.webp 1020w" />
                      </div>
                      <div className="success-card _02">
                        <div className="success-no">
                          02
                        </div>
                        <div className="success-detail">
                          <div className="success-year">
                            2018
                          </div>
                          <div className="success-card-name">
                            Design Award
                          </div>
                        </div>
                        <img alt="Success Image" className="success-image" loading="lazy" sizes="(max-width: 1360px) 100vw, 1360px" src="/assets/images/Success-Image-2_1.webp" srcSet="/assets/images/Success-Image-2_1Success-Image-2.webp 500w, /assets/images/Success-Image-2_1Success-Image-2.webp 800w, /assets/images/Success-Image-2_1Success-Image-2.webp 1080w, /assets/images/Success-Image-2_1.webp 1360w" />
                      </div>
                      <div className="success-card _03">
                        <div className="success-no">
                          03
                        </div>
                        <div className="success-detail">
                          <div className="success-year">
                            2022
                          </div>
                          <div className="success-card-name">
                            Good Design Award
                          </div>
                        </div>
                        <img alt="Success Image" className="success-image" loading="lazy" sizes="(max-width: 1360px) 100vw, 1360px" src="/assets/images/Success-Image-3_1.webp" srcSet="/assets/images/Success-Image-3_1Success-Image-3.webp 500w, /assets/images/Success-Image-3_1Success-Image-3.webp 800w, /assets/images/Success-Image-3_1Success-Image-3.webp 1080w, /assets/images/Success-Image-3_1.webp 1360w" />
                      </div>
                      <div className="success-card _04">
                        <div className="success-no">
                          04
                        </div>
                        <div className="success-detail">
                          <div className="success-year">
                            2024
                          </div>
                          <div className="success-card-name">
                            Core 77 - Design Awards
                          </div>
                        </div>
                        <img alt="Success Image" className="success-image" loading="lazy" sizes="(max-width: 1360px) 100vw, 1360px" src="/assets/images/Success-Image-4_1.webp" srcSet="/assets/images/Success-Image-4_1Success-Image-4.webp 500w, /assets/images/Success-Image-4_1Success-Image-4.webp 800w, /assets/images/Success-Image-4_1Success-Image-4.webp 1080w, /assets/images/Success-Image-4_1.webp 1360w" />
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="testimonial-section">
                <div className="container large-container">
                  <div className="wrapper about-testimonial-wrapper">
                    <div className="choose-top">
                      <div className="subtitle-block reveal">
                        <div className="typography-title">
                          Testimonial
                        </div>
                      </div>
                      <h2 className="heading-h2 reveal">
                        Loved by Teams Worldwide
                      </h2>
                      <p className="center-align about-test reveal">
                        See how Virion helps businesses simplify analytics, save time, and make smarter decisions every day.
                      </p>
                    </div>
                    <div className="about-testimonial-slider reveal">
                      <div className="about-testimonial-mask">
                        <div className="about-testimonial-slide">
                          <div className="about-slider-content">
                            <div>
                              <div className="about-img-overflow">
                                <img alt="About Slider Img" className="about-slider-img" loading="lazy" src="/assets/images/About-Slider-Img-1.webp" />
                              </div>
                              <div className="slider-bottom tab">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Kathryn Murphy
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                            <div className="slider-right-content">
                              <div className="slider-top">
                                <div className="space-between">
                                  <img alt="Slider Logo" className="slider-logo" loading="lazy" src="/assets/images/Slider-Logo-2.webp" />
                                  <img alt="Slider Quote Icon" className="slider-quote-icon" loading="lazy" src="/assets/images/Vector_1.webp" />
                                </div>
                                <p className="small-paragraph slider-para">
                                  "Before switching, our reporting process was a nightmare — disconnected tools, manual data entry, and constant back-and-forth to verify numbers. It felt like we were always a step behind. Now, everything’s in one place, updated in real time, and accessible to everyone who needs it.
                                  <br />
                                  <br />
                                  We’ve cut our reporting time by over 80%, and the insights we get are actually actionable. Teams across product, sales, and customer success are finally on the same page, making decisions faster and with more confidence."
                                </p>
                              </div>
                              <div className="slider-bottom desk">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Leslie Alexander
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="about-testimonial-slide">
                          <div className="about-slider-content">
                            <div>
                              <div className="about-img-overflow">
                                <img alt="About Slider Img" className="about-slider-img" loading="lazy" src="/assets/images/About-Slider-Img-2.webp" />
                              </div>
                              <div className="slider-bottom tab">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Kathryn Murphy
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                            <div className="slider-right-content">
                              <div className="slider-top">
                                <div className="space-between">
                                  <img alt="Slider Logo" className="slider-logo" loading="lazy" src="/assets/images/Slider-Logo-1.webp" />
                                  <img alt="Slider Quote Icon" className="slider-quote-icon" loading="lazy" src="/assets/images/Vector_1.webp" />
                                </div>
                                <p className="small-paragraph slider-para">
                                  “our team was drowning in spreadsheets and wasting hours building reports that were outdated the moment they were shared. Since switching, everything has changed. We now have real-time dashboards that update automatically, predictive insights that help us spot opportunities early, and reports that take minutes instead of days.
                                  <br />
                                  <br />
                                  The collaboration features make it easy for our marketing, sales, and finance teams to stay aligned because everyone is working from the same live data.”
                                </p>
                              </div>
                              <div className="slider-bottom desk">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Kathryn Murphy
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="about-testimonial-slide">
                          <div className="about-slider-content">
                            <div>
                              <div className="about-img-overflow">
                                <img alt="About Slider Img" className="about-slider-img" loading="lazy" src="/assets/images/About-Slider-Img.webp" />
                              </div>
                              <div className="slider-bottom tab">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Kathryn Murphy
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                            <div className="slider-right-content">
                              <div className="slider-top">
                                <div className="space-between">
                                  <img alt="Slider Logo" className="slider-logo" loading="lazy" src="/assets/images/Slider-Logo-3.webp" />
                                  <img alt="Slider Quote Icon" className="slider-quote-icon" loading="lazy" src="/assets/images/Vector_1.webp" />
                                </div>
                                <p className="small-paragraph slider-para">
                                  "We used to spend countless hours chasing data from different sources, manually compiling everything just to get a partial view of performance. It was frustrating and time-consuming. After making the switch, we have a single source of truth with real-time visibility across departments, and the time we save is incredible.
                                  <br />
                                  <br />
                                  The automation and AI-driven insights have helped us forecast more accurately, respond faster to changes, and make smarter decisions as a team.”
                                </p>
                              </div>
                              <div className="slider-bottom desk">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Devon Lane
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="about-testimonial-slide">
                          <div className="about-slider-content">
                            <div>
                              <div className="about-img-overflow">
                                <img alt="About Slider Img" className="about-slider-img" loading="lazy" sizes="(max-width: 840px) 100vw, 840px" src="/assets/images/About-Slider-Img-4_1.webp" srcSet="/assets/images/About-Slider-Img-4_1About-Slider-Img-4.webp 500w, /assets/images/About-Slider-Img-4_1About-Slider-Img-4.webp 800w, /assets/images/About-Slider-Img-4_1.webp 840w" />
                              </div>
                              <div className="slider-bottom tab">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Kathryn Murphy
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                            <div className="slider-right-content">
                              <div className="slider-top">
                                <div className="space-between">
                                  <img alt="Slider Logo" className="slider-logo" loading="lazy" src="/assets/images/Slider-Logo-1.webp" />
                                  <img alt="Slider Quote Icon" className="slider-quote-icon" loading="lazy" src="/assets/images/Vector_1.webp" />
                                </div>
                                <p className="small-paragraph slider-para">
                                  "We used to spend countless hours chasing data from different sources, manually compiling everything just to get a partial view of performance. It was frustrating and time-consuming. After making the switch, we have a single source of truth with real-time visibility across departments, and the time we save is incredible.
                                  <br />
                                  <br />
                                  The automation and AI-driven insights have helped us forecast more accurately, respond faster to changes, and make smarter decisions as a team.”
                                </p>
                              </div>
                              <div className="slider-bottom desk">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Aanya Patel
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="about-testimonial-slide">
                          <div className="about-slider-content">
                            <div>
                              <div className="about-img-overflow">
                                <img alt="About Slider Img" className="about-slider-img" loading="lazy" sizes="(max-width: 840px) 100vw, 840px" src="/assets/images/About-Slider-Img-5_1.webp" srcSet="/assets/images/About-Slider-Img-5_1About-Slider-Img-5.webp 500w, /assets/images/About-Slider-Img-5_1About-Slider-Img-5.webp 800w, /assets/images/About-Slider-Img-5_1.webp 840w" />
                              </div>
                              <div className="slider-bottom tab">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Kathryn Murphy
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                            <div className="slider-right-content">
                              <div className="slider-top">
                                <div className="space-between">
                                  <img alt="Slider Logo" className="slider-logo" loading="lazy" src="/assets/images/Slider-Logo-1.webp" />
                                  <img alt="Slider Quote Icon" className="slider-quote-icon" loading="lazy" src="/assets/images/Vector_1.webp" />
                                </div>
                                <p className="small-paragraph slider-para">
                                  "We used to spend countless hours chasing data from different sources, manually compiling everything just to get a partial view of performance. It was frustrating and time-consuming. After making the switch, we have a single source of truth with real-time visibility across departments, and the time we save is incredible.
                                  <br />
                                  <br />
                                  The automation and AI-driven insights have helped us forecast more accurately, respond faster to changes, and make smarter decisions as a team.”
                                </p>
                              </div>
                              <div className="slider-bottom desk">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Emily Johnson
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="about-testimonial-slide">
                          <div className="about-slider-content">
                            <div>
                              <div className="about-img-overflow">
                                <img alt="About Slider Img" className="about-slider-img" loading="lazy" sizes="(max-width: 840px) 100vw, 840px" src="/assets/images/About-Slider-Img-6_1.webp" srcSet="/assets/images/About-Slider-Img-6_1About-Slider-Img-6.webp 500w, /assets/images/About-Slider-Img-6_1About-Slider-Img-6.webp 800w, /assets/images/About-Slider-Img-6_1.webp 840w" />
                              </div>
                              <div className="slider-bottom tab">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Kathryn Murphy
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                            <div className="slider-right-content">
                              <div className="slider-top">
                                <div className="space-between">
                                  <img alt="Slider Logo" className="slider-logo" loading="lazy" src="/assets/images/Slider-Logo-1.webp" />
                                  <img alt="Slider Quote Icon" className="slider-quote-icon" loading="lazy" src="/assets/images/Vector_1.webp" />
                                </div>
                                <p className="small-paragraph slider-para">
                                  "We used to spend countless hours chasing data from different sources, manually compiling everything just to get a partial view of performance. It was frustrating and time-consuming. After making the switch, we have a single source of truth with real-time visibility across departments, and the time we save is incredible.
                                  <br />
                                  <br />
                                  The automation and AI-driven insights have helped us forecast more accurately, respond faster to changes, and make smarter decisions as a team.”
                                </p>
                              </div>
                              <div className="slider-bottom desk">
                                <div className="slider-flex">
                                  <div className="slider-author-name">
                                    Mei Lin
                                  </div>
                                  <div className="small-paragraph slider-author-designation">
                                    Operations Manager
                                  </div>
                                </div>
                                <a className="linkedin" href="https://www.linkedin.com/" target="_blank">
                                  <svg className="linkedin-icon" fill="none" viewBox="0 0 30 30" width="100%" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M27.2863 0H2.71374C1.215 0 0 1.215 0 2.71374V27.2862C0 28.785 1.215 30 2.71374 30H27.2862C28.785 30 30 28.785 30 27.2862V2.71374C30 1.215 28.785 0 27.2863 0ZM9.28327 25.904C9.28327 26.3402 8.92971 26.6937 8.49353 26.6937H5.13181C4.69563 26.6937 4.34207 26.3402 4.34207 25.904V11.8118C4.34207 11.3756 4.69563 11.022 5.13181 11.022H8.49353C8.92971 11.022 9.28327 11.3756 9.28327 11.8118V25.904ZM6.81267 9.69361C5.04887 9.69361 3.61901 8.26374 3.61901 6.49995C3.61901 4.73615 5.04887 3.30628 6.81267 3.30628C8.57647 3.30628 10.0063 4.73615 10.0063 6.49995C10.0063 8.26374 8.57654 9.69361 6.81267 9.69361ZM26.8516 25.9676C26.8516 26.3686 26.5264 26.6937 26.1254 26.6937H22.5181C22.1171 26.6937 21.7919 26.3686 21.7919 25.9676V19.3575C21.7919 18.3715 22.0812 15.0365 19.215 15.0365C16.9918 15.0365 16.5408 17.3192 16.4503 18.3436V25.9676C16.4503 26.3686 16.1252 26.6937 15.7242 26.6937H12.2352C11.8342 26.6937 11.5091 26.3686 11.5091 25.9676V11.7481C11.5091 11.3471 11.8342 11.022 12.2352 11.022H15.7242C16.1252 11.022 16.4503 11.3471 16.4503 11.7481V12.9776C17.2747 11.7404 18.4998 10.7855 21.1083 10.7855C26.8846 10.7855 26.8516 16.1821 26.8516 19.1472V25.9676Z" fill="currentColor">
                                    </path>
                                  </svg>
                                  <div className="seo">
                                    SEO
                                  </div>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="left-arrow-about">
                        <div>
                        </div>
                      </div>
                      <div className="right-arrow-about">
                        <div>
                        </div>
                      </div>
                      <div className="about-slide-nav">
                      </div>
                    </div>
                  </div>
                </div>
                <div className="slider-gradient-left">
                </div>
                <div className="slider-gradient-right">
                </div>
              </section>
              <section className="cta-section">
                <div className="container large-container">
                  <div className="wrapper cta-wrapper">
                    <div className="cta-wrap">
                      <div className="cta-flex">
                        <h2 className="white-text cta-title">
                          Unlock Smarter Analytics Now
                        </h2>
                        <p className="cta-para">
                          Start free today or book a demo to see how Virion transforms your data.
                        </p>
                        <div className="cta-buttons">
                          <a className="cta-button" href="/contact">
                            <div className="text-overflow">
                              <div className="button-text _01">
                                Get Started
                              </div>
                              <div className="button-text _02">
                                Get Started
                              </div>
                            </div>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
    </>
  );
}
