// AUTO-GENERATED by scripts/convert-all.mjs. Markup mirrors the original template;
// styling comes from /assets/css/styles.css. Re-run the script to regenerate.
export default function LoginPage() {
  return (
    <>
      <section className="login-section">
                <div className="container login-container">
                  <div className="wrapper login-wrapper">
                    <div className="login-form-block">
                      <form className="login-form" data-demo-form="1" data-name="Login Form" id="wf-form-Login-Form" name="wf-form-Login-Form">
                        <div className="login-form-header">
                          <div className="lock-block">
                            <div className="lock-box">
                              <img alt="Lock Icon" className="lock-icon" src="/assets/images/user-line.webp" />
                            </div>
                          </div>
                          <h4 className="password-title">
                            Login to your account
                          </h4>
                          <p className="password-para">
                            Enter your details to login.
                          </p>
                        </div>
                        <div className="login-flex _01">
                          <label className="small-paragraph pw-text" htmlFor="Login-Email">
                            Email Address
                            <span className="required-icon">
                              *
                            </span>
                          </label>
                          <input className="login-text-field" data-name="Login Email" id="Login-Email" maxLength={256} name="Login-Email" placeholder="hello@alignui.com" required type="email" />
                        </div>
                        <div className="login-flex _02">
                          <label className="small-paragraph pw-text" htmlFor="Login-Password">
                            Password
                            <span className="required-icon">
                              *
                            </span>
                          </label>
                          <input className="password-text-field" data-name="Login Password" id="Login-Password" maxLength={256} name="Login-Password" placeholder="• • • • • • • • • • " required type="password" />
                        </div>
                        <input className="password-button" type="submit" value="Login" />
                      </form>
                      <div className="login-success-message" data-form-done="1" hidden>
                        <div>
                          Thank you! Your submission has been received!
                        </div>
                      </div>
                      <div className="login-error-message" data-form-fail="1" hidden>
                        <div>
                          Oops! Something went wrong while submitting the form.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
    </>
  );
}
